[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools>=40.8.0",
    "wheel",
    "numpy",
	"cython>=0.29.30",
    "matplotlib",
    "meshio",
    "pyparsing",
    "scipy",
    "tables",
]
